# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IQsmhRgDE2Xz6rjwnxovC9umq74WgK7nRr1cnZonrAA3CObl94WEZKcEolpRFQ6uDf0Kvop5NXUMG5DhaRmPvWUFjGcg1CK46uHlpmDKMXWO7IKOAbwRoQEBx1rgq4w6A8as7IVaUCgZaAcY/yF9EgsxWBKK92vqzZ4DmFd7ZLoN6kZPTd1AcYIZpwo+eX3BNhuBanCR+KKfwO0Sat20K1m5ckTaxYQZnVLYzvWCG9FpSSrWnuRqH/HbPkgbVayBUT6kDRgb6rSm4wxIkd8QoZHV0HhIqSF5AzB1baQkIc3iOGO5RzNtpTSYw1ftEo5G0QmsoEjVp+or83ZwHioNnZiUCOQj4i7/6un8mRNmil4Tqge46q3LSchXqmiDhFrN7ROEBDA9477jIiuGYUYQ7gpOeFmBd/1GrPnlkeWH+5CbPyzyW5FpmkOfEUi/BXYWoThinYx6Jh/XHMsmGGQCj5byvV9T9FDxYtCpI3qEo4fpO2LQPmHmAJ1GBolA03XWL0//ZH5WiXvzB56LU5NtpBqKYznvWO7Vo77hVvbyL7P6/VByY/SIgRRzrrM61F8oDj8ElIDRrQFltZZh5EYnDPioWVnJDKkTqVCQyzKA1nROSmG6zANP3ZVnEbcOqISVTng59W3pHmZvvjjQhJVCTLceB5uW/F/hqUh9KuM4myI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
